### ISSUE TITLE
cljs build errors

### ISSUE THREAD

**Issue by kevincolyar** [qerub/camel-snake-kebab#20] opened 2014-10-27 23:13 UTC
I'm using camel-snake-kebab in a cljs (+Om) project and I'm having trouble when any type of error occurs (syntax error, etc, unrelated to using camel-snake-kebab).  I get the following error in my browser:

    Uncaught Error: Undefined nameToPath for camel_snake_kebab.core 

and I'm unable to recompile using `lein cljsbuild auto`.  I have to completely rebuild the project to remove the error.

**Comment by qerub** [comment] 2015-01-11 00:12
Closing since this isn't an issue with this library but with ClojureScript tooling. I've been unable to replicate this (maybe because I'm using a newer `lein-cljsbuild`), but a Google search on the error message reveals that other users are affected (with other libraries) as well.

**Closed by qerub** 2015-01-11 00:12 UTC

**Comment by tlightsky** [comment] 2015-03-04 06:53
When using with clojurescript. I meet this problem with too
```
clojure.lang.ExceptionInfo : No such namespace: camel-snake-kebab.core at line 1?
```
my versions:
```
[org.clojure/clojure "1.6.0"]
[org.clojure/clojurescript "0.0-2755"]It gives me this 

[lein-cljsbuild "1.0.5"] 
```


also,it gives me some hint like this while lein deps
```
WARNING!!! version ranges found for:
[camel-snake-kebab "0.3.1"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [org.clojure/clojure "[1.3.0,)"]
Consider using [camel-snake-kebab "0.3.1" :exclusions [org.clojure/clojure]].
[camel-snake-kebab "0.3.1"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/regex "1.1.0"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [camel-snake-kebab "0.3.1" :exclusions [org.clojure/clojure]].
[camel-snake-kebab "0.3.1"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/parsley "0.9.1"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [camel-snake-kebab "0.3.1" :exclusions [org.clojure/clojure]].
[camel-snake-kebab "0.3.1"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/parsley "0.9.1"] -> [net.cgrand/regex "1.1.0"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [camel-snake-kebab "0.3.1" :exclusions [org.clojure/clojure]].
```

**Comment by qerub** [comment] 2015-03-07 20:10
Can you provide an example project that exhibits this problem? (I don't know how to reproduce what you're observing.)

The version range warning is unharmful, but ugly. I've filed a separate issue (#28) to care about that.

**Comment by tlightsky** [comment] 2015-03-09 10:50
I find I forget the -> before kebab-case,it wors well now :+1:
